### ISSUE TITLE
Tracking Issue: Static Website

### ISSUE THREAD

**Issue by yutotakano** [compsoc-edinburgh/cook-book#18]
This issue tracks the progress/ideas/features for the upcoming static website for this repo. Any insight is welcome!

- [x] Stylesheets and Images to make it authentic, while keeping filesizes low and browse compatibility maximum.
- [x] Tags (for cousine, dietary stuff, etc), meal types, allergens
- [x] Comments (using Giscus, synced with GitHub Discussions)
- [x] Minimal changes to this repo as possible (all website boilerplate is in `compsoc-edinburgh/cookbook-boilerplate`)
- [x] Use the first image (if any) in the recipe markdown as the _feature image_
- [ ] Ability store favourites/bookmarks in `localStorage`
- [x] A clear and very simple template to add new recipes
- [ ] JavaScript to change the serving amount and recalculate all the ingredients
- [ ] Meet accessibility thresholds and provide a Accessibility Statement (via https://www.accessibilitystatementgenerator.com/)
- [x] Search (on a static site?)
